apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: contoso-dev-aks2-cluster
  namespace: flux-system
spec:
  interval: 2m
  destroyResourcesOnDeletion: true
  approvePlan: auto
  path: ./aks-cluster
  sourceRef:
    kind: GitRepository
    name: aks-playground-source
    namespace: flux-system
  runnerPodTemplate:
    spec:
      envFrom:
        - secretRef:
            name: azure-tf-credentials
  enableInventory: true
  vars:
    - name: spoke_name
      value: jm-contoso-dev
    - name: spoke_resource_group_name
      value: jm-contoso-dev-rg
    - name: spoke_vnet_name
      value: vnet-spoke-jm-contoso-dev-001
    - name: aks_cluster_name
      value: contoso-dev-aks2
    - name: aks_subnet_name
      value: contoso-dev-aks1-node-subnet
    - name: location
      value: eastus
    - name: network_plugin_mode
      value: overlay
    - name: ebpf_data_plane
      value: cilium
    - name: hub_resource_group_name
      value: "contoso-hub-rg"
    - name: privatelink_subnet_name
      value: "sn-plendpoints"
    - name: environment
      value: dev
